name: CI/CD DevSecOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:

    # 1. Récupérer le code
    - name: Checkout
      uses: actions/checkout@v3

    # 2. Installer dépendances
    - name: Install dependencies
      run: npm install

    # 3. Build
    - name: Build
      run: npm run build

    # 4. Tests
    - name: Run tests
      run: npm test

    # 5. Snyk (dépendances)
    - name: Snyk scan
      uses: snyk/actions/node@master
      env:
        SNYK_API: ${{ secrets.SNYK_API }}

    # 6. SonarQube (SAST)
    - name: SonarQube scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONARQUBE_API: ${{ secrets.SONARQUBE_API }}

    # 7. GitGuardian (secrets)
    - name: GitGuardian scan
      uses: GitGuardian/ggshield-action@master
      env:
        GITGUARDIAN_API: ${{ secrets.GITGUARDIAN_API }}

    # 8. Déploiement (simulation)
    - name: Deploy
      run: echo "Déploiement sécurisé"
