name: Pipeline DevSecOps SaaS Jira

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  security:
    name: Analyse Sécurité Globale
    runs-on: ubuntu-latest
    
    steps:
      # 1. Récupération du code
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Préparation de Node.js
      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Installation des dépendances
      - name: Installation des dépendances
        run: npm install

      # --- ÉTAPE 1 : SNYK (Sécurité Bibliothèques / SCA) ---
      - name: Scan Snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API }}

      # --- ÉTAPE 2 : DEEPSOURCE (Analyse Qualité & Failles / SAST) ---
      # On utilise ton secret DEEPSOURCE_API (le DSN sous forme de lien)
      - name: DeepSource Analysis
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --token ${{ secrets.DEEPSOURCE_API }}
        continue-on-error: true

      # --- ÉTAPE 3 : GITGUARDIAN (Détection de Secrets) ---
      - name: Scan GitGuardian
        uses: GitGuardian/ggshield-action@master
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API }}

  validation:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - name: Rapport Final
        run: echo "Analyse multi-outils (Snyk, DeepSource, GitGuardian) terminée avec succès !"
